
---
spring:
  profiles: subject,primary
words: I,You,He,She,It
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: verb,primary
words: ran,knew,had,saw,bought
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: article,primary
words: a,the
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: adjective,primary
words: reasonable,leaky,suspicious,ordinary,unlikely
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: noun,primary
words: boat,book,vote,seat,backpack,partition,groundhog        
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: subject,secondary
words: I,You,He,She,It
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: verb,secondary
words: ran,knew,had,saw,bought
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: article,secondary
words: a,the
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: adjective,secondary
words: reasonable,leaky,suspicious,ordinary,unlikely
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
---
spring:
  profiles: noun,secondary
words: boat,book,vote,seat,backpack,partition,groundhog        
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/